// <auto-generated />
using System;
using IssuePit.Notes.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IssuePit.Notes.Core.Data.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20260330040524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "WorkspaceId");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.NoteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer");

                    b.Property<string>("RawLinkText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetNoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceNoteId");

                    b.HasIndex("TargetNoteId");

                    b.ToTable("note_links");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.NoteWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitRepositoryUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("LinkedProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StorageEngine")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("note_workspaces");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.Note", b =>
                {
                    b.HasOne("IssuePit.Notes.Core.Entities.NoteWorkspace", "Workspace")
                        .WithMany("Notes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.NoteLink", b =>
                {
                    b.HasOne("IssuePit.Notes.Core.Entities.Note", "SourceNote")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Notes.Core.Entities.Note", "TargetNote")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetNoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceNote");

                    b.Navigation("TargetNote");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.Note", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });

            modelBuilder.Entity("IssuePit.Notes.Core.Entities.NoteWorkspace", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
