// <auto-generated />
using System;
using IssuePit.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IssuePit.Core.Migrations
{
    [DbContext(typeof(IssuePitDbContext))]
    [Migration("20260314121926_AddProjectRequiresRunApproval")]
    partial class AddProjectRequiresRunApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssuePit.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTools")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DisableInternet")
                        .HasColumnType("boolean");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RunnerType")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentMcpServer", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId", "McpServerId");

                    b.HasIndex("McpServerId");

                    b.ToTable("agent_mcp_servers");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentOrg", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId", "OrgId");

                    b.HasIndex("OrgId");

                    b.ToTable("agent_orgs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentProject", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.HasKey("AgentId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("agent_projects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IssueTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RuntimeConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("IssueId");

                    b.HasIndex("IssueTaskId");

                    b.HasIndex("RuntimeConfigId");

                    b.ToTable("agent_sessions");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentSessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stream")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.ToTable("agent_session_logs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("api_keys");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CiCdRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CiCdRunId");

                    b.ToTable("cicd_artifacts");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalRunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InputsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Workflow")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorkflowGraphJson")
                        .HasColumnType("text");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("cicd_runs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CiCdRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Stream")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CiCdRunId");

                    b.ToTable("cicd_run_logs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdTestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CiCdTestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MethodName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CiCdTestSuiteId");

                    b.ToTable("cicd_test_cases");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdTestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CiCdRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("FailedTests")
                        .HasColumnType("integer");

                    b.Property<int>("PassedTests")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedTests")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTests")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CiCdRunId");

                    b.ToTable("cicd_test_suites");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CodeReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextAfter")
                        .HasColumnType("text");

                    b.Property<string>("ContextBefore")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Snippet")
                        .HasColumnType("text");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("code_review_comments");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GitHubUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("UserId");

                    b.ToTable("github_identities");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentityOrg", b =>
                {
                    b.Property<Guid>("GitHubIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasKey("GitHubIdentityId", "OrgId");

                    b.HasIndex("OrgId");

                    b.ToTable("github_identity_orgs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentityProject", b =>
                {
                    b.Property<Guid>("GitHubIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("GitHubIdentityId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("github_identity_projects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownCommitSha")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ThrottledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("git_repositories");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitBranch")
                        .HasColumnType("text");

                    b.Property<int?>("GitHubIssueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubIssueUrl")
                        .HasColumnType("text");

                    b.Property<int>("KanbanRank")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ParentIssueId");

                    b.HasIndex("ProjectId");

                    b.ToTable("issues");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueAssignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("IssueId");

                    b.HasIndex("UserId");

                    b.ToTable("issue_assignees");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVoiceFile")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UserId");

                    b.ToTable("issue_attachments");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UserId");

                    b.ToTable("issue_comments");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorAgentId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("IssueId");

                    b.ToTable("issue_events");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("TargetIssueId");

                    b.ToTable("issue_links");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitBranch")
                        .HasColumnType("text");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("IssueId");

                    b.ToTable("issue_tasks");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("kanban_boards");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("IssueStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("kanban_columns");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromColumnId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToColumnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BoardId");

                    b.HasIndex("FromColumnId");

                    b.HasIndex("ToColumnId");

                    b.ToTable("kanban_transitions");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("labels");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTools")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("mcp_servers");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerProject", b =>
                {
                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("McpServerId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("mcp_server_projects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerProjectAgent", b =>
                {
                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.HasKey("McpServerId", "ProjectId", "AgentId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("mcp_server_project_agents");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.ToTable("mcp_server_secrets");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoMergeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastCiCdRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastKnownSourceSha")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MergeCommitSha")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastCiCdRunId");

                    b.HasIndex("ProjectId");

                    b.ToTable("merge_requests");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("milestones");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActEnv")
                        .HasColumnType("text");

                    b.Property<string>("ActRunnerImage")
                        .HasColumnType("text");

                    b.Property<string>("ActSecrets")
                        .HasColumnType("text");

                    b.Property<string>("ActionCachePath")
                        .HasColumnType("text");

                    b.Property<bool>("ActionOfflineMode")
                        .HasColumnType("boolean");

                    b.Property<int?>("ConcurrentJobs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalRepositories")
                        .HasColumnType("text");

                    b.Property<int>("MaxConcurrentRunners")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UseNewActionCache")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("OrgId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("org_members");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActEnv")
                        .HasColumnType("text");

                    b.Property<string>("ActRunnerImage")
                        .HasColumnType("text");

                    b.Property<string>("ActSecrets")
                        .HasColumnType("text");

                    b.Property<string>("ActionCachePath")
                        .HasColumnType("text");

                    b.Property<bool?>("ActionOfflineMode")
                        .HasColumnType("boolean");

                    b.Property<int?>("ConcurrentJobs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GitHubRepo")
                        .HasColumnType("text");

                    b.Property<bool>("IsAgenda")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueKey")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("IssueNumberOffset")
                        .HasColumnType("integer");

                    b.Property<string>("LocalRepositories")
                        .HasColumnType("text");

                    b.Property<int>("MaxConcurrentRunners")
                        .HasColumnType("integer");

                    b.Property<bool>("MountRepositoryInDocker")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresRunApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("UseNewActionCache")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("project_members");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ProjectMetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DoneIssues")
                        .HasColumnType("integer");

                    b.Property<int>("InProgressIssues")
                        .HasColumnType("integer");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAgentRuns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCiCdRuns")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_metric_snapshots");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.RuntimeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentAgents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("runtime_configurations");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GitAuthToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitAuthUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitRepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitSubDir")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("team_members");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TelegramBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DigestInterval")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedBotToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSilent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("ProjectId");

                    b.ToTable("telegram_bots");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseConnectionString")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RecurringInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("todos");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("todo_boards");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoBoardMembership", b =>
                {
                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.HasKey("TodoId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("todo_board_memberships");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("todo_categories");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoCategoryMembership", b =>
                {
                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("TodoId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("todo_category_memberships");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("issue_labels", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelsId")
                        .HasColumnType("uuid");

                    b.HasKey("IssueId", "LabelsId");

                    b.HasIndex("LabelsId");

                    b.ToTable("issue_labels");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Agent", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentMcpServer", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany("AgentMcpServers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.McpServer", "McpServer")
                        .WithMany("AgentMcpServers")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentOrg", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany("AgentOrgs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentProject", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany("AgentProjects")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentSession", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.IssueTask", "IssueTask")
                        .WithMany()
                        .HasForeignKey("IssueTaskId");

                    b.HasOne("IssuePit.Core.Entities.RuntimeConfiguration", "RuntimeConfig")
                        .WithMany()
                        .HasForeignKey("RuntimeConfigId");

                    b.Navigation("Agent");

                    b.Navigation("Issue");

                    b.Navigation("IssueTask");

                    b.Navigation("RuntimeConfig");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentSessionLog", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.AgentSession", "AgentSession")
                        .WithMany("Logs")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("IssuePit.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdArtifact", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.CiCdRun", "CiCdRun")
                        .WithMany()
                        .HasForeignKey("CiCdRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiCdRun");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdRun", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.AgentSession", "AgentSession")
                        .WithMany("CiCdRuns")
                        .HasForeignKey("AgentSessionId");

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdRunLog", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.CiCdRun", "CiCdRun")
                        .WithMany("Logs")
                        .HasForeignKey("CiCdRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiCdRun");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdTestCase", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.CiCdTestSuite", "CiCdTestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("CiCdTestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiCdTestSuite");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdTestSuite", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.CiCdRun", "CiCdRun")
                        .WithMany()
                        .HasForeignKey("CiCdRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiCdRun");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CodeReviewComment", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentity", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentityOrg", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.GitHubIdentity", "GitHubIdentity")
                        .WithMany("Orgs")
                        .HasForeignKey("GitHubIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitHubIdentity");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentityProject", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.GitHubIdentity", "GitHubIdentity")
                        .WithMany("Projects")
                        .HasForeignKey("GitHubIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitHubIdentity");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitRepository", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Issue", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId");

                    b.HasOne("IssuePit.Core.Entities.Issue", "ParentIssue")
                        .WithMany("SubIssues")
                        .HasForeignKey("ParentIssueId");

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("ParentIssue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueAssignee", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany("Assignees")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Agent");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueAttachment", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueComment", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueEvent", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "ActorAgent")
                        .WithMany()
                        .HasForeignKey("ActorAgentId");

                    b.HasOne("IssuePit.Core.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorAgent");

                    b.Navigation("ActorUser");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueLink", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany("Links")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Issue", "TargetIssue")
                        .WithMany()
                        .HasForeignKey("TargetIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("TargetIssue");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.IssueTask", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("IssuePit.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanBoard", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanColumn", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.KanbanBoard", "KanbanBoard")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanBoard");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanTransition", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("IssuePit.Core.Entities.KanbanBoard", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.KanbanColumn", "FromColumn")
                        .WithMany()
                        .HasForeignKey("FromColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.KanbanColumn", "ToColumn")
                        .WithMany()
                        .HasForeignKey("ToColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Board");

                    b.Navigation("FromColumn");

                    b.Navigation("ToColumn");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Label", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerProject", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.McpServer", "McpServer")
                        .WithMany("McpServerProjects")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerProjectAgent", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.McpServer", "McpServer")
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("McpServer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServerSecret", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.McpServer", "McpServer")
                        .WithMany("Secrets")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.MergeRequest", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.CiCdRun", "LastCiCdRun")
                        .WithMany()
                        .HasForeignKey("LastCiCdRunId");

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastCiCdRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Milestone", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Organization", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.OrganizationMember", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Project", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ProjectMember", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.ProjectMetricSnapshot", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.RuntimeConfiguration", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Skill", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Team", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TeamMember", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TelegramBot", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId");

                    b.HasOne("IssuePit.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Todo", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoBoard", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoBoardMembership", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.TodoBoard", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Todo", "Todo")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoCategory", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.TodoBoard", "Board")
                        .WithMany("Categories")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoCategoryMembership", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.TodoCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Todo", "Todo")
                        .WithMany("CategoryMemberships")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.User", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("issue_labels", b =>
                {
                    b.HasOne("IssuePit.Core.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssuePit.Core.Entities.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Agent", b =>
                {
                    b.Navigation("AgentMcpServers");

                    b.Navigation("AgentOrgs");

                    b.Navigation("AgentProjects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.AgentSession", b =>
                {
                    b.Navigation("CiCdRuns");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdRun", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.CiCdTestSuite", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.GitHubIdentity", b =>
                {
                    b.Navigation("Orgs");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Issue", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Links");

                    b.Navigation("SubIssues");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.KanbanBoard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.McpServer", b =>
                {
                    b.Navigation("AgentMcpServers");

                    b.Navigation("McpServerProjects");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.Todo", b =>
                {
                    b.Navigation("BoardMemberships");

                    b.Navigation("CategoryMemberships");
                });

            modelBuilder.Entity("IssuePit.Core.Entities.TodoBoard", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
